import '@/shared/styles/index.css';
import 'swiper/css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import React, { Suspense } from 'react';

import Providers from '@/app/providers';
import { AuthModal } from '@/feature/session/auth';
import { BottomNavbar, Footer, Header } from '@/widgets';

const gilroy = localFont({
    src: [
        {
            path: '../shared/assets/fonts/Gilroy-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../shared/assets/fonts/Gilroy-Medium.ttf',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../shared/assets/fonts/Gilroy-Semibold.ttf',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../shared/assets/fonts/Gilroy-Bold.ttf',
            weight: '700',
            style: 'normal',
        },
    ],
    variable: '--font-gilroy',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className={gilroy.className}>
            <body>
                <Providers>
                    <div className={'layout'}>
                        <Header />
                        <main>
                            {children}
                            <BottomNavbar />
                            <Suspense fallback={<div></div>}>
                                <AuthModal />
                            </Suspense>
                        </main>
                        <Footer />
                    </div>
                    <div id={'portal'} />
                </Providers>
            </body>
        </html>
    );
}
