export { Advantages } from './Advantages';
export { CallBanner, MainBanner, NewCollectionBanner, QuestionBanner } from './Banners';
export { BottomNavbar } from './BottomNavbar';
export { CategoriesList } from './CategoriesList';
export { Footer } from './Footer';
export { Header } from './Header';
export { ProductsCarousel } from './ProductsCarousel';
export { ProductsList } from './ProductsList';
export { RecentProduct } from './RecentProducts';
export { SideNavigation } from './SideNavigation';
