export { Advantages } from './Advantages';
export { CallBanner, MainBanner, NewCollectionBanner, QuestionBanner } from './Banners';
export { CategoriesList } from './CategoriesList';
export { FavoritesList } from './FavoritesList';
export { Footer } from './Footer';
export { Header } from './Header';
export { MobileNavbar } from './MobileNavbar';
export { ProductsCarousel } from './ProductsCarousel';
export { ProductsList } from './ProductsList';
export { RecentProduct } from './RecentsProducts';
export { SideNavigation } from './SideNavigation';
